package com.smart_finance_app

import androidx.compose.runtime.Composable
import androidx.compose.runtime.ReadOnlyComposable

/**
 * Returns the localised string for the current language set in LocaleController.
 * This bypasses the Compose resource system's locale mechanism entirely and
 * reads directly from our own string maps.
 */
@Composable
@ReadOnlyComposable
fun appStringResource(key: StringKey): String {
    val lang = LocaleController.currentLanguageCode
    return AppStrings.get(lang, key)
}

enum class StringKey {
    // Navigation
    NAV_DASHBOARD, NAV_TRANSACTIONS, NAV_ACCOUNTS, NAV_BUDGETS,
    NAV_REPORTS, NAV_GOALS, NAV_SETTINGS,

    // Sign in
    SIGNIN_TITLE, SIGNIN_SUBTITLE, SIGNIN_EMAIL, SIGNIN_PASSWORD,
    SIGNIN_FORGOT_PASSWORD, SIGNIN_BUTTON, SIGNIN_BUTTON_LOADING,
    SIGNIN_NO_ACCOUNT, SIGNIN_CREATE_ACCOUNT,

    // Registration
    REGISTER_TITLE, REGISTER_FULL_NAME, REGISTER_EMAIL, REGISTER_PASSWORD,
    REGISTER_CONFIRM_PASSWORD, REGISTER_BUTTON, REGISTER_BUTTON_LOADING,
    REGISTER_ALREADY_HAVE_ACCOUNT, REGISTER_SIGN_IN,
    REGISTER_SHOW_PASSWORD, REGISTER_HIDE_PASSWORD,

    // Forgot password
    FORGOT_PASSWORD_TITLE, FORGOT_PASSWORD_SUBTITLE, FORGOT_PASSWORD_EMAIL_LABEL,
    FORGOT_PASSWORD_EMAIL_PLACEHOLDER, FORGOT_PASSWORD_SEND_BUTTON, FORGOT_PASSWORD_BACK,
    FORGOT_PASSWORD_SECURITY_TITLE, FORGOT_PASSWORD_SECURITY_SUBTITLE,
    FORGOT_PASSWORD_INVALID_EMAIL,

    // Reset password
    RESET_PASSWORD_TITLE, RESET_PASSWORD_SUBTITLE, RESET_PASSWORD_NEW_LABEL,
    RESET_PASSWORD_CONFIRM_LABEL, RESET_PASSWORD_BUTTON, RESET_PASSWORD_BACK,
    RESET_PASSWORD_EXPIRED_TITLE, RESET_PASSWORD_EXPIRED_DESCRIPTION,
    RESET_PASSWORD_EXPIRED_MESSAGE, RESET_PASSWORD_SUCCESS_TITLE,
    RESET_PASSWORD_SUCCESS_DESCRIPTION, RESET_PASSWORD_SUCCESS_MESSAGE,
    RESET_PASSWORD_ERROR_LENGTH, RESET_PASSWORD_ERROR_MISMATCH,

    // Dashboard
    DASHBOARD_GREETING_MORNING, DASHBOARD_GREETING_AFTERNOON, DASHBOARD_GREETING_NIGHT,
    DASHBOARD_LOADING, DASHBOARD_ERROR_TITLE, DASHBOARD_RETRY,
    DASHBOARD_NO_ACCOUNTS_TITLE, DASHBOARD_NO_ACCOUNTS_SUBTITLE,
    DASHBOARD_CONNECT_ACCOUNT, DASHBOARD_ALL_ACCOUNTS, DASHBOARD_ADD_CHARTS,
    DASHBOARD_ALL_CHARTS_ADDED, DASHBOARD_CHART_SIZE_FULL, DASHBOARD_CHART_SIZE_HALF,
    DASHBOARD_ADD_BUTTON, DASHBOARD_VIEW_ALL, DASHBOARD_INCOME, DASHBOARD_EXPENSES,
    DASHBOARD_SPENDING_OVERVIEW, DASHBOARD_RECENT_TRANSACTIONS,
    DASHBOARD_CONNECTED_ACCOUNTS, DASHBOARD_SUBTITLE, DASHBOARD_MONTHLY_TREND,
    DASHBOARD_MONTHLY_COMPARISON, DASHBOARD_ACCOUNTS_OVERVIEW, DASHBOARD_ADD_ACCOUNT,
    DASHBOARD_QUICK_ACTIONS, DASHBOARD_BUDGET_PROGRESS, DASHBOARD_DONE,
    DASHBOARD_CUSTOMISE, DASHBOARD_CHARTS_BUTTON, DASHBOARD_CURRENT_BALANCE,
    DASHBOARD_VS_LAST_MONTH, DASHBOARD_UPCOMING_BILLS, DASHBOARD_NO_UPCOMING_BILLS,
    DASHBOARD_WEEKLY, DASHBOARD_MONTHLY, DASHBOARD_DUE,
    DASHBOARD_HIGHEST_SPENDING, DASHBOARD_ACCOUNTS_COUNT,

    // Spending periods
    PERIOD_THIS_MONTH, PERIOD_LAST_MONTH, PERIOD_LAST_3_MONTHS, PERIOD_THIS_YEAR,
    DASHBOARD_SPENDING_PERIOD,

    // Chart titles and descriptions
    CHART_WEEKLY_SPENDING_TITLE, CHART_WEEKLY_SPENDING_DESC,
    CHART_SPENDING_PER_DAY_TITLE, CHART_SPENDING_PER_DAY_DESC,
    CHART_BANK_COMPARISON_TITLE, CHART_BANK_COMPARISON_DESC,
    CHART_TIME_OF_DAY_TITLE, CHART_TIME_OF_DAY_DESC,
    CHART_LARGEST_TX_TITLE, CHART_LARGEST_TX_DESC,
    CHART_SMALLEST_TX_TITLE, CHART_SMALLEST_TX_DESC,
    CHART_MERCHANT_FREQUENCY_TITLE, CHART_MERCHANT_FREQUENCY_DESC,
    CHART_UPCOMING_BILLS_TITLE, CHART_UPCOMING_BILLS_DESC,

    // Transactions
    TRANSACTIONS_TITLE, TRANSACTIONS_SEARCH_PLACEHOLDER,
    TRANSACTIONS_FILTER_ALL, TRANSACTIONS_FILTER_INCOME, TRANSACTIONS_FILTER_EXPENSES,
    TRANSACTIONS_LOADING, TRANSACTIONS_EMPTY, TRANSACTIONS_PREVIOUS, TRANSACTIONS_NEXT,
    TRANSACTIONS_COL_DATE, TRANSACTIONS_COL_MERCHANT, TRANSACTIONS_COL_CATEGORY,
    TRANSACTIONS_COL_ACCOUNT, TRANSACTIONS_COL_AMOUNT, TRANSACTIONS_COL_ACTIONS,
    TRANSACTIONS_EDIT,

    // Categories
    CATEGORY_FOOD_DINING, CATEGORY_SHOPPING_PERSONAL, CATEGORY_BILLS_HOUSING,
    CATEGORY_ENTERTAINMENT_SUBSCRIPTIONS, CATEGORY_TRANSPORTATION,
    CATEGORY_TRANSFERS, CATEGORY_INCOME, CATEGORY_OTHERS,

    // Accounts
    ACCOUNTS_TITLE, ACCOUNTS_SUBTITLE, ACCOUNTS_YOUR_ACCOUNTS, ACCOUNTS_EMPTY,
    ACCOUNTS_CONNECT_BANK, ACCOUNTS_CONNECT_SEARCH_HINT,
    ACCOUNTS_STATUS_CONNECTED, ACCOUNTS_STATUS_DISCONNECTED,
    ACCOUNTS_CONSENT_TITLE, ACCOUNTS_CONSENT_BODY_1, ACCOUNTS_CONSENT_BODY_2,
    ACCOUNTS_CONSENT_CANCEL, ACCOUNTS_CONSENT_CONTINUE,

    // Connect bank
    CONNECT_BANK_TITLE, CONNECT_BANK_SUBTITLE, CONNECT_BANK_SEARCH_PLACEHOLDER,
    CONNECT_BANK_POPULAR, CONNECT_BANK_LOADING, CONNECT_BANK_NOT_FOUND,
    CONNECT_BANK_CANT_FIND, CONNECT_BANK_CONTINUE, CONNECT_BANK_CONNECTING,
    CONNECT_BANK_CANCEL, CONNECT_BANK_BACK, CONNECT_BANK_READONLY_NOTICE,

    // Budgets
    BUDGETS_TITLE, BUDGETS_ADD, BUDGETS_EMPTY_TITLE, BUDGETS_EMPTY_SUBTITLE,
    BUDGETS_OF, BUDGETS_SPENT, BUDGETS_REMAINING, BUDGETS_OVER_BY,
    BUDGETS_DIALOG_ADD_TITLE, BUDGETS_DIALOG_EDIT_TITLE, BUDGETS_DIALOG_CATEGORY,
    BUDGETS_DIALOG_PERIOD, BUDGETS_DIALOG_LIMIT, BUDGETS_DIALOG_PERIOD_MONTHLY,
    BUDGETS_DIALOG_PERIOD_WEEKLY, BUDGETS_DIALOG_CATEGORY_SET,
    BUDGETS_DIALOG_CANCEL, BUDGETS_DIALOG_SAVE, BUDGETS_DIALOG_ADD_BUTTON,
    BUDGETS_DIALOG_AMOUNT_ERROR, BUDGETS_EDIT, BUDGETS_DELETE,

    // Plan
    PLAN_TITLE, PLAN_BACK, PLAN_FREE_TITLE, PLAN_FREE_PRICE,
    PLAN_FREE_PRICE_DETAIL_TOP, PLAN_FREE_PRICE_DETAIL_BOTTOM,
    PLAN_FREE_BUTTON_CURRENT, PLAN_FREE_BUTTON, PLAN_BASIC_TITLE,
    PLAN_BASIC_SUBTITLE, PLAN_BASIC_PRICE, PLAN_BASIC_PRICE_DETAIL_TOP,
    PLAN_BASIC_PRICE_DETAIL_BOTTOM, PLAN_BASIC_BUTTON_CURRENT, PLAN_BASIC_BUTTON,

    // Payment
    PAYMENT_TITLE, PAYMENT_SUBTITLE, PAYMENT_LOADING, PAYMENT_CURRENT_PLAN,
    PAYMENT_NO_CARD_TITLE, PAYMENT_NO_CARD_BODY, PAYMENT_NO_CARD_FOUND,
    PAYMENT_UPDATE_BUTTON, PAYMENT_UPDATING_BUTTON, PAYMENT_CHANGE_PLAN,
    PAYMENT_SUBSCRIBE_PROMPT, PAYMENT_VIEW_PLANS, PAYMENT_CARD_ENDING,
    PAYMENT_CARD_EXPIRES, PAYMENT_HISTORY_TITLE, PAYMENT_HISTORY_EMPTY,
    PAYMENT_INVOICE_FALLBACK, PAYMENT_INVOICE_UNKNOWN_STATUS,
    PAYMENT_BILLING_INFO_TITLE, PAYMENT_BILLING_NAME, PAYMENT_BILLING_EMAIL,
    PAYMENT_BILLING_ADDRESS, PAYMENT_BILLING_NOT_PROVIDED, PAYMENT_BILLING_UPDATE,
    PAYMENT_CANCEL_PAID_PROMPT, PAYMENT_CANCEL_FREE_PROMPT,
    PAYMENT_CANCEL_BUTTON, PAYMENT_CANCEL_OPENING,

    // Consent
    CONSENT_TITLE, CONSENT_SUBTITLE, CONSENT_ITEM_BALANCES, CONSENT_ITEM_TRANSACTIONS,
    CONSENT_ITEM_NO_MOVE_MONEY, CONSENT_ITEM_NO_PAYMENTS, CONSENT_DATA_SECURE,
    CONSENT_AGREEMENT_CHECKBOX, CONSENT_CONTINUE, CONSENT_CANCEL,

    // Settings
    SETTINGS_TITLE, SETTINGS_SECTION_ACCOUNT, SETTINGS_SECTION_PREFERENCES,
    SETTINGS_SECTION_SUBSCRIPTION, SETTINGS_SECTION_DANGER,
    SETTINGS_PROFILE, SETTINGS_APPEARANCE, SETTINGS_LANGUAGE, SETTINGS_CURRENCY,
    SETTINGS_NOTIFICATIONS, SETTINGS_MANAGE_SUBSCRIPTION, SETTINGS_SIGN_OUT,
    SETTINGS_DELETE_ACCOUNT, SETTINGS_SIGN_OUT_CONFIRM_TITLE,
    SETTINGS_SIGN_OUT_CONFIRM_MESSAGE, SETTINGS_SIGN_OUT_CONFIRM_BUTTON,
    SETTINGS_CANCEL, SETTINGS_LANGUAGE_DIALOG_TITLE, SETTINGS_CURRENCY_DIALOG_TITLE,

    // Language names
    LANG_EN, LANG_ES, LANG_FR, LANG_NL, LANG_DE, LANG_IT, LANG_PL, LANG_ZH_TW,

    // Common
    COMMON_BACK, COMMON_CANCEL, COMMON_SAVE, COMMON_RETRY, COMMON_LOADING,
    COMMON_ERROR_SERVER, COMMON_SESSION_EXPIRED, COMMON_COMING_SOON,

    // Edit Profile
    EDIT_PROFILE_TITLE, EDIT_PROFILE_SUBTITLE, EDIT_PROFILE_FULL_NAME,
    EDIT_PROFILE_EMAIL, EDIT_PROFILE_EMAIL_INVALID, EDIT_PROFILE_UPDATE_PASSWORD,
    EDIT_PROFILE_SAVE, EDIT_PROFILE_SAVING, EDIT_PROFILE_CANCEL,
    EDIT_PROFILE_SUCCESS, EDIT_PROFILE_CONFIRM_PASSWORD_TITLE,
    EDIT_PROFILE_CONFIRM_PASSWORD_BODY, EDIT_PROFILE_CURRENT_PASSWORD,
    EDIT_PROFILE_CONFIRM, EDIT_PROFILE_BACK,

// Update Password
    UPDATE_PASSWORD_TITLE, UPDATE_PASSWORD_SUBTITLE, UPDATE_PASSWORD_CURRENT,
    UPDATE_PASSWORD_NEW, UPDATE_PASSWORD_CONFIRM, UPDATE_PASSWORD_BUTTON,
    UPDATE_PASSWORD_UPDATING, UPDATE_PASSWORD_CANCEL, UPDATE_PASSWORD_BACK,
    UPDATE_PASSWORD_SUCCESS_TITLE, UPDATE_PASSWORD_SUCCESS_BODY,
    UPDATE_PASSWORD_OK, UPDATE_PASSWORD_ERROR_CURRENT_REQUIRED,
    UPDATE_PASSWORD_ERROR_LENGTH, UPDATE_PASSWORD_ERROR_MISMATCH,
}